name: Test
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: github-token
        uses: ./
        with:
          from: '${{ toJson(secrets) }}'
          name: 'GITHUB_TOKEN'
      - run: echo ${{ steps.github-token.outputs.exists }}

